angular.module("app").service("service", function() {

  function randomNum() {
      return Math.floor(Math.random() * 1000);
  }

  var categories = [
    {
      name: "Holidays",
      url: "./img/holidays.jpg",
    },

    {
      name: "Architecture",
      url: "./img/architecture.jpg",
    },
    {
      name: "Nature",
      url: "./img/nature.jpg",
    },
    {
      name: "Food & Drink",
      url: "./img/food.jpg",
    },
    {
      name: "Business",
      url: "./img/business.jpg",
    },
    {
      name: "Animals",
      url: "./img/animals.jpg",
    },
    {
      name: "People",
      url: "./img/people.jpg",
    },
    {
      name: "Fashion",
      url: "./img/fashion.jpg",
    }
  ];

  this.getCategories = function() {
    return categories;
  };

  var images = [
    {
      name: "Breakfast in Bed",
      url: "./img/breakfast in bed.jpg",
      likes: randomNum(),
      category: "Food & Drink",
      description: "Eating Breakfast in Bed",
    },
    {
      name: "Bridge",
      url: "./img/bridge.jpg",
      likes: randomNum(),
      category: "Architecture",
      description: "Scenic Shot of the Brooklyn Bridge",
    },
    {
      name: "Bumble Bee",
      url: "./img/bumble bee.jpg",
      likes: randomNum(),
      category: "Animals",
      description: "A Bumble Bee on a Flower",
    },
    {
      name: "Business Blazer",
      url: "./img/business blazer.jpg",
      likes: randomNum(),
      category: "Business",
      description: "Man at a Desk in a Blazer",
    },
    {
      name: "Calendar",
      url: "./img/calendar.jpg",
      likes: randomNum(),
      category: "Business",
      description: "A Calendar App on an iPad",
    },
    {
      name: "Car Phone",
      url: "./img/car phone.jpg",
      likes: randomNum(),
      category: "Business",
      description: "A Man Talking on the Phone in His Car",
    },
    {
      name: "Cat",
      url: "./img/cat.jpg",
      likes: randomNum(),
      category: "Animals",
      description: "A Cute Cat",
    },
    {
      name: "Christmas Decoration",
      url: "./img/christmas decoration.jpg",
      likes: randomNum(),
      category: "Holidays",
      description: "A Christmas Decoration at a Shopping Mall",
    },
    {
      name: "Christmas Dinner",
      url: "./img/christmas dinner.jpg",
      likes: randomNum(),
      category: "Holidays",
      description: "A Delicious Christmas Dinner",
    },
    {
      name: "Christmas Presents",
      url: "./img/christmas presents.jpg",
      likes: randomNum(),
      category: "Holidays",
      description: "Christmas Presents Sitting Under a Christmas Tree",
    },
    {
      name: "Christmas Table",
      url: "./img/christmas table.jpg",
      likes: randomNum(),
      category: "Holidays",
      description: "Christmas Table Centerpiece with Decorations",
    },
    {
      name: "Christmas Wrapping",
      url: "./img/christmas wrapping.jpg",
      likes: randomNum(),
      category: "Holidays",
      description: "Wrapping Christmas Presents",
    },
    {
      name: "City",
      url: "./img/city.jpg",
      likes: randomNum(),
      category: "Architecture",
      description: "Looking Up At New York City Skyscrapers",
    },
    {
      name: "Closeup",
      url: "./img/Closeup.jpg",
      likes: randomNum(),
      category: "People",
      description: "A Closup Photo of a Girl",
    },
    {
      name: "Coding",
      url: "./img/Coding.jpg",
      likes: randomNum(),
      category: "Business",
      description: "Writing Some Awesome Code!",
    },
    {
      name: "Colonnade",
      url: "./img/colonnade.jpg",
      likes: randomNum(),
      category: "Architecture",
      description: "Some Nice Column Architecture",
    },
    {
      name: "Computer and Book",
      url: "./img/computer and book.jpg",
      likes: randomNum(),
      category: "Business",
      description: "A Computer, a Book, a Notepad, and a Phone",
    },
    {
      name: "Diary",
      url: "./img/diary.jpg",
      likes: randomNum(),
      category: "Business",
      description: "Writing Down Some Thoughts in a Diary",
    },
    {
      name: "Donuts",
      url: "./img/donuts.jpg",
      likes: randomNum(),
      category: "Food & Drink",
      description: "Some Delicious Donuts",
    },
    {
      name: "Fireworks",
      url: "./img/fireworks.jpg",
      likes: randomNum(),
      category: "Holidays",
      description: "Fireworks on the Fourth of July",
    },
    {
      name: "Foggy Mountains",
      url: "./img/foggy mountains.jpg",
      likes: randomNum(),
      category: "Nature",
      description: "Fog Sitting on the Tops of Mountains",
    },
    {
      name: "Fresh Berries",
      url: "./img/fresh berries.jpg",
      likes: randomNum(),
      category: "Food & Drink",
      description: "A Bowl Filled With Fresh Stawberries and Berries",
    },
    {
      name: "Fresh Strawberry Cake",
      url: "./img/fresh strawberry cake.jpg",
      likes: randomNum(),
      category: "Food & Drink",
      description: "A Yummy Strawberry Cake",
    },
    {
      name: "Girl in Hat",
      url: "./img/girl in hat.jpg",
      likes: randomNum(),
      category: "Fashion",
      description: "A Hat With Sunset",
    },
    {
      name: "Girl in Venice",
      url: "./img/girl in venice.jpg",
      likes: randomNum(),
      category: "People",
      description: "A Girl Looking at Gondolas in Venice",
    },
    {
      name: "Girl With Landscape",
      url: "./img/girl with landscape.jpg",
      likes: randomNum(),
      category: "Fashion",
      description: "A Well Dressed Girl with a Landscape",
    },
    {
      name: "Ground Coffee",
      url: "./img/ground coffee.jpg",
      likes: randomNum(),
      category: "Food & Drink",
      description: "Some Freshly Ground Coffee",
    },
    {
      name: "Heels",
      url: "./img/heels.jpg",
      likes: randomNum(),
      category: "Fashion",
      description: "Heels Sticking Out of a Car Window",
    },
    {
      name: "Hexagon Architecture",
      url: "./img/hexagon architecture.jpg",
      likes: randomNum(),
      category: "Architecture",
      description: "A Dome Made of Hexagons",
    },
    {
      name: "High Mountains",
      url: "./img/high mountains.jpg",
      likes: randomNum(),
      category: "Nature",
      description: "Trails Winding Through Rocky Mountains",
    },
    {
      name: "Horse",
      url: "./img/horse.jpg",
      likes: randomNum(),
      category: "Animals",
      description: "A Horse In a Harness",
    },
    {
      name: "Jacket",
      url: "./img/jacket.jpg",
      likes: randomNum(),
      category: "Fashion",
      description: "A Fashionable Jacket",
    },
    {
      name: "Jewelry Box",
      url: "./img/jewelry box.jpg",
      likes: randomNum(),
      category: "Fashion",
      description: "A Drawer Filled with Jewelry",
    },
    {
      name: "Jogging",
      url: "./img/jogging.jpg",
      likes: randomNum(),
      category: "People",
      description: "A Jogger Running On a Bridge",
    },
    {
      name: "Laying in Bed",
      url: "./img/laying in bed.jpg",
      likes: randomNum(),
      category: "People",
      description: "A Woman in a Bodysuit Laying in Bed",
    },
    {
      name: "Looking Up",
      url: "./img/Looking Up.jpg",
      likes: randomNum(),
      category: "People",
      description: "Looking Up at Space",
    },
    {
      name: "Meditation",
      url: "./img/meditation.jpg",
      likes: randomNum(),
      category: "People",
      description: "A Girl Meditating",
    },
    {
      name: "Minimalist Office Workspace",
      url: "./img/minimalist office workspace.jpg",
      likes: randomNum(),
      category: "People",
      description: "A Minimalist Workspace with Computers and Technology",
    },
    {
      name: "Mountain",
      url: "./img/Mountain.jpg",
      likes: randomNum(),
      category: "Nature",
      description: "A Climber On Top Of a Mountain",
    },
    {
      name: "Pancakes",
      url: "./img/pancakes.jpg",
      likes: randomNum(),
      category: "Food & Drink",
      description: "A Stack of Pancakes with Berries",
    },
    {
      name: "Pizza",
      url: "./img/pizza.jpg",
      likes: randomNum(),
      category: "Food & Drink",
      description: "Pizza!",
    },
    {
      name: "Prague Castle",
      url: "./img/prague castle.jpg",
      likes: randomNum(),
      category: "Architecture",
      description: "A Night View of a Castle in Prague",
    },
    {
      name: "Prague Old Town",
      url: "./img/prague old town.jpg",
      likes: randomNum(),
      category: "Architecture",
      description: "A City Overlook in the City of Prague",
    },
    {
      name: "Prague Town Square",
      url: "./img/prague town square.jpg",
      likes: randomNum(),
      category: "Architecture",
      description: "A Town Square in the City of Prague",
    },
    {
      name: "Sea Waves",
      url: "./img/sea waves.jpg",
      likes: randomNum(),
      category: "Nature",
      description: "Waves in the Ocean",
    },
    {
      name: "Smoothie",
      url: "./img/smoothie.jpg",
      likes: randomNum(),
      category: "Food & Drink",
      description: "A Delicious Smoothie and Fruit",
    },
    {
      name: "Snowy Forest",
      url: "./img/snowy forest.jpg",
      likes: randomNum(),
      category: "Nature",
      description: "Snow Covered Trees On a Mountain",
    },
    {
      name: "Sparkler",
      url: "./img/sparkler.jpg",
      likes: randomNum(),
      category: "Holidays",
      description: "A Sparkler Burning Down",
    },
    {
      name: "Spring Bloom",
      url: "./img/spring bloom.jpg",
      likes: randomNum(),
      category: "Nature",
      description: "A Flower Blooming",
    },
    {
      name: "Steel Bridge",
      url: "./img/steel bridge.jpg",
      likes: randomNum(),
      category: "Architecture",
      description: "A Steel Bridge",
    },
    {
      name: "Sunglasses",
      url: "./img/sunglasses.jpg",
      likes: randomNum(),
      category: "Fashion",
      description: "A Cool Pair of Sunglasses",
    },
    {
      name: "Sunhat",
      url: "./img/sunhat.jpg",
      likes: randomNum(),
      category: "Fashion",
      description: "A Woman Walking with a Fashionable Hat",
    },
    {
      name: "Swans",
      url: "./img/swans.jpg",
      likes: randomNum(),
      category: "Animals",
      description: "Swans Swimming in a Lake",
    },
    {
      name: "Swimming",
      url: "./img/swimming.jpg",
      likes: randomNum(),
      category: "People",
      description: "A Woman Swimming in a Pool",
    },
    {
      name: "Teaching",
      url: "./img/teaching.jpg",
      likes: randomNum(),
      category: "Business",
      description: "A Man Teaching a Class",
    },
    {
      name: "Valentines Day",
      url: "./img/valentines day.jpg",
      likes: randomNum(),
      category: "Holidays",
      description: "A Romantic Valentines Day Dinner",
    },
    {
      name: "Watch",
      url: "./img/watch.jpg",
      likes: randomNum(),
      category: "Fashion",
      description: "Checking a Fashionable Watch",
    },
    {
      name: "Web Design Skeleton",
      url: "./img/web design skeleton.jpg",
      likes: randomNum(),
      category: "Business",
      description: "Sketching Out a Skeleton for a Website",
    },
    {
      name: "Winter Mountains",
      url: "./img/winter mountains.jpg",
      likes: randomNum(),
      category: "Nature",
      description: "A Wide Shot of Mountains During the Winter",
    },
    {
      name: "Yellow Flower Field",
      url: "./img/yellow flower field.jpg",
      likes: randomNum(),
      category: "Nature",
      description: "A Field Filled with Yellow Flowers",
    },
    {
      name: "Yorkie in Grass",
      url: "./img/yorkie in grass.jpg",
      likes: randomNum(),
      category: "Animals",
      description: "A Cute Little Yorie in the Grass",
    },
    {
      name: "Yorkie Puppy",
      url: "./img/yorkie puppy.jpg",
      likes: randomNum(),
      category: "Animals",
      description: "An Adorable Yorkie Puppy",
    },
    {
      name: "Yorkie Waiting for Food",
      url: "./img/yorkie waiting for food.jpg",
      likes: randomNum(),
      category: "Animals",
      description: "An Adorable Yorkie Waiting For It's Food",
    },
    {
      name: "Yorkie With Clothes",
      url: "./img/yorkie with clothes.jpg",
      likes: randomNum(),
      category: "Animals",
      description: "An Yorkie Wearing a Sweater",
    },
  ];


  this.getImages = function() {
    return images;
  };

});
